package com.team.emofood.dto;

import lombok.Data;

@Data
public class FoodMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_menu.fid
     *
     * @mbg.generated Sun Oct 23 17:51:32 KST 2022
     */
    private int fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_menu.fname
     *
     * @mbg.generated Sun Oct 23 17:51:32 KST 2022
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_menu.fprice
     *
     * @mbg.generated Sun Oct 23 17:51:32 KST 2022
     */
    private String fprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_menu.fimg
     *
     * @mbg.generated Sun Oct 23 17:51:32 KST 2022
     */
    private String fimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_menu.rid
     *
     * @mbg.generated Sun Oct 23 17:51:32 KST 2022
     */
    private int rid;
}