package com.team.emofood.dto;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uemail
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    private String uemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upw
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    private String upw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ugend
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    private Byte ugend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uage
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    private Integer uage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ujoindate
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    private Date ujoindate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uemail
     *
     * @return the value of user.uemail
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uemail
     *
     * @param uemail the value for user.uemail
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public void setUemail(String uemail) {
        this.uemail = uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upw
     *
     * @return the value of user.upw
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public String getUpw() {
        return upw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upw
     *
     * @param upw the value for user.upw
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public void setUpw(String upw) {
        this.upw = upw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ugend
     *
     * @return the value of user.ugend
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public Byte getUgend() {
        return ugend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ugend
     *
     * @param ugend the value for user.ugend
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public void setUgend(Byte ugend) {
        this.ugend = ugend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uage
     *
     * @return the value of user.uage
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public Integer getUage() {
        return uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uage
     *
     * @param uage the value for user.uage
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public void setUage(Integer uage) {
        this.uage = uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ujoindate
     *
     * @return the value of user.ujoindate
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public Date getUjoindate() {
        return ujoindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ujoindate
     *
     * @param ujoindate the value for user.ujoindate
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public void setUjoindate(Date ujoindate) {
        this.ujoindate = ujoindate;
    }
}