package com.team.emofood.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public UserExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUemailIsNull() {
            addCriterion("uemail is null");
            return (Criteria) this;
        }

        public Criteria andUemailIsNotNull() {
            addCriterion("uemail is not null");
            return (Criteria) this;
        }

        public Criteria andUemailEqualTo(String value) {
            addCriterion("uemail =", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotEqualTo(String value) {
            addCriterion("uemail <>", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailGreaterThan(String value) {
            addCriterion("uemail >", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailGreaterThanOrEqualTo(String value) {
            addCriterion("uemail >=", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLessThan(String value) {
            addCriterion("uemail <", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLessThanOrEqualTo(String value) {
            addCriterion("uemail <=", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailLike(String value) {
            addCriterion("uemail like", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotLike(String value) {
            addCriterion("uemail not like", value, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailIn(List<String> values) {
            addCriterion("uemail in", values, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotIn(List<String> values) {
            addCriterion("uemail not in", values, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailBetween(String value1, String value2) {
            addCriterion("uemail between", value1, value2, "uemail");
            return (Criteria) this;
        }

        public Criteria andUemailNotBetween(String value1, String value2) {
            addCriterion("uemail not between", value1, value2, "uemail");
            return (Criteria) this;
        }

        public Criteria andUnameIsNull() {
            addCriterion("uname is null");
            return (Criteria) this;
        }

        public Criteria andUnameIsNotNull() {
            addCriterion("uname is not null");
            return (Criteria) this;
        }

        public Criteria andUnameEqualTo(String value) {
            addCriterion("uname =", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotEqualTo(String value) {
            addCriterion("uname <>", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThan(String value) {
            addCriterion("uname >", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThanOrEqualTo(String value) {
            addCriterion("uname >=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThan(String value) {
            addCriterion("uname <", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThanOrEqualTo(String value) {
            addCriterion("uname <=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLike(String value) {
            addCriterion("uname like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotLike(String value) {
            addCriterion("uname not like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameIn(List<String> values) {
            addCriterion("uname in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotIn(List<String> values) {
            addCriterion("uname not in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameBetween(String value1, String value2) {
            addCriterion("uname between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotBetween(String value1, String value2) {
            addCriterion("uname not between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUpwIsNull() {
            addCriterion("upw is null");
            return (Criteria) this;
        }

        public Criteria andUpwIsNotNull() {
            addCriterion("upw is not null");
            return (Criteria) this;
        }

        public Criteria andUpwEqualTo(String value) {
            addCriterion("upw =", value, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwNotEqualTo(String value) {
            addCriterion("upw <>", value, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwGreaterThan(String value) {
            addCriterion("upw >", value, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwGreaterThanOrEqualTo(String value) {
            addCriterion("upw >=", value, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwLessThan(String value) {
            addCriterion("upw <", value, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwLessThanOrEqualTo(String value) {
            addCriterion("upw <=", value, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwLike(String value) {
            addCriterion("upw like", value, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwNotLike(String value) {
            addCriterion("upw not like", value, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwIn(List<String> values) {
            addCriterion("upw in", values, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwNotIn(List<String> values) {
            addCriterion("upw not in", values, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwBetween(String value1, String value2) {
            addCriterion("upw between", value1, value2, "upw");
            return (Criteria) this;
        }

        public Criteria andUpwNotBetween(String value1, String value2) {
            addCriterion("upw not between", value1, value2, "upw");
            return (Criteria) this;
        }

        public Criteria andUgendIsNull() {
            addCriterion("ugend is null");
            return (Criteria) this;
        }

        public Criteria andUgendIsNotNull() {
            addCriterion("ugend is not null");
            return (Criteria) this;
        }

        public Criteria andUgendEqualTo(Byte value) {
            addCriterion("ugend =", value, "ugend");
            return (Criteria) this;
        }

        public Criteria andUgendNotEqualTo(Byte value) {
            addCriterion("ugend <>", value, "ugend");
            return (Criteria) this;
        }

        public Criteria andUgendGreaterThan(Byte value) {
            addCriterion("ugend >", value, "ugend");
            return (Criteria) this;
        }

        public Criteria andUgendGreaterThanOrEqualTo(Byte value) {
            addCriterion("ugend >=", value, "ugend");
            return (Criteria) this;
        }

        public Criteria andUgendLessThan(Byte value) {
            addCriterion("ugend <", value, "ugend");
            return (Criteria) this;
        }

        public Criteria andUgendLessThanOrEqualTo(Byte value) {
            addCriterion("ugend <=", value, "ugend");
            return (Criteria) this;
        }

        public Criteria andUgendIn(List<Byte> values) {
            addCriterion("ugend in", values, "ugend");
            return (Criteria) this;
        }

        public Criteria andUgendNotIn(List<Byte> values) {
            addCriterion("ugend not in", values, "ugend");
            return (Criteria) this;
        }

        public Criteria andUgendBetween(Byte value1, Byte value2) {
            addCriterion("ugend between", value1, value2, "ugend");
            return (Criteria) this;
        }

        public Criteria andUgendNotBetween(Byte value1, Byte value2) {
            addCriterion("ugend not between", value1, value2, "ugend");
            return (Criteria) this;
        }

        public Criteria andUageIsNull() {
            addCriterion("uage is null");
            return (Criteria) this;
        }

        public Criteria andUageIsNotNull() {
            addCriterion("uage is not null");
            return (Criteria) this;
        }

        public Criteria andUageEqualTo(Integer value) {
            addCriterion("uage =", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageNotEqualTo(Integer value) {
            addCriterion("uage <>", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageGreaterThan(Integer value) {
            addCriterion("uage >", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageGreaterThanOrEqualTo(Integer value) {
            addCriterion("uage >=", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageLessThan(Integer value) {
            addCriterion("uage <", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageLessThanOrEqualTo(Integer value) {
            addCriterion("uage <=", value, "uage");
            return (Criteria) this;
        }

        public Criteria andUageIn(List<Integer> values) {
            addCriterion("uage in", values, "uage");
            return (Criteria) this;
        }

        public Criteria andUageNotIn(List<Integer> values) {
            addCriterion("uage not in", values, "uage");
            return (Criteria) this;
        }

        public Criteria andUageBetween(Integer value1, Integer value2) {
            addCriterion("uage between", value1, value2, "uage");
            return (Criteria) this;
        }

        public Criteria andUageNotBetween(Integer value1, Integer value2) {
            addCriterion("uage not between", value1, value2, "uage");
            return (Criteria) this;
        }

        public Criteria andUjoindateIsNull() {
            addCriterion("ujoindate is null");
            return (Criteria) this;
        }

        public Criteria andUjoindateIsNotNull() {
            addCriterion("ujoindate is not null");
            return (Criteria) this;
        }

        public Criteria andUjoindateEqualTo(Date value) {
            addCriterion("ujoindate =", value, "ujoindate");
            return (Criteria) this;
        }

        public Criteria andUjoindateNotEqualTo(Date value) {
            addCriterion("ujoindate <>", value, "ujoindate");
            return (Criteria) this;
        }

        public Criteria andUjoindateGreaterThan(Date value) {
            addCriterion("ujoindate >", value, "ujoindate");
            return (Criteria) this;
        }

        public Criteria andUjoindateGreaterThanOrEqualTo(Date value) {
            addCriterion("ujoindate >=", value, "ujoindate");
            return (Criteria) this;
        }

        public Criteria andUjoindateLessThan(Date value) {
            addCriterion("ujoindate <", value, "ujoindate");
            return (Criteria) this;
        }

        public Criteria andUjoindateLessThanOrEqualTo(Date value) {
            addCriterion("ujoindate <=", value, "ujoindate");
            return (Criteria) this;
        }

        public Criteria andUjoindateIn(List<Date> values) {
            addCriterion("ujoindate in", values, "ujoindate");
            return (Criteria) this;
        }

        public Criteria andUjoindateNotIn(List<Date> values) {
            addCriterion("ujoindate not in", values, "ujoindate");
            return (Criteria) this;
        }

        public Criteria andUjoindateBetween(Date value1, Date value2) {
            addCriterion("ujoindate between", value1, value2, "ujoindate");
            return (Criteria) this;
        }

        public Criteria andUjoindateNotBetween(Date value1, Date value2) {
            addCriterion("ujoindate not between", value1, value2, "ujoindate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 24 16:44:56 KST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Mon Oct 24 16:44:56 KST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}