package com.team.emofood.mapper;
import com.team.emofood.dto.EmotLog;
import com.team.emofood.dto.EmotLogExample;
import com.team.emofood.util.PageQueryUtil;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface EmotLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    long countByExample(EmotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    int deleteByExample(EmotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    int insert(EmotLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    int insertSelective(EmotLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    List<EmotLog> selectByExample(EmotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    EmotLog selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    int updateByExampleSelective(@Param("row") EmotLog row, @Param("example") EmotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    int updateByExample(@Param("row") EmotLog row, @Param("example") EmotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    int updateByPrimaryKeySelective(EmotLog row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emot_log
     *
     * @mbg.generated Sun Oct 23 17:52:15 KST 2022
     */
    int updateByPrimaryKey(EmotLog row);

    List<EmotLog> findEmotLogList(PageQueryUtil pageUtil);
    int getTotalEmotLog(PageQueryUtil pageUtil);
}