package com.team.emofood.mapper;

import com.team.emofood.dto.KakaoInfo;
import com.team.emofood.dto.KakaoInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface KakaoInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    long countByExample(KakaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    int deleteByExample(KakaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    int deleteByPrimaryKey(Integer kid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    int insert(KakaoInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    int insertSelective(KakaoInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    List<KakaoInfo> selectByExample(KakaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    KakaoInfo selectByPrimaryKey(Integer kid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    int updateByExampleSelective(@Param("row") KakaoInfo row, @Param("example") KakaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    int updateByExample(@Param("row") KakaoInfo row, @Param("example") KakaoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    int updateByPrimaryKeySelective(KakaoInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kakao_info
     *
     * @mbg.generated Sun Oct 23 17:41:39 KST 2022
     */
    int updateByPrimaryKey(KakaoInfo row);
}