package com.team.emofood.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.team.emofood.dto.User;
import com.team.emofood.dto.UserExample;
import com.team.emofood.dto.UserKey;
import com.team.emofood.dto.UserWithBLOBs;
import com.team.emofood.util.PageQueryUtil;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    int deleteByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    int insert(UserWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    int insertSelective(UserWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    List<UserWithBLOBs> selectByExampleWithBLOBs(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    UserWithBLOBs selectByPrimaryKey(UserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    int updateByExampleSelective(@Param("row") UserWithBLOBs row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") UserWithBLOBs row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    int updateByPrimaryKeySelective(UserWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    int updateByPrimaryKeyWithBLOBs(UserWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sun Oct 23 17:51:53 KST 2022
     */
    int updateByPrimaryKey(User row);

    List<User> findUserList(PageQueryUtil pageUtil);
    int getTotalUser(PageQueryUtil pageUtil);

    // 로그인
    User getUserAccount(String userId);

    // 회원가입
    void saveUser(User user);
}